### PR TITLE
Many changes

### PR DESCRIPTION
**Pull request by TheTechRobo**
- Spelling/grammar
- Readability
- Remove mass quantities of whitespace in README.md
- Slight code improvement
- Switch to Python gitignore (why would you want to ignore `icons`, also this new one ignores everything you'd want to ignore)

Things I did not do:

- Correct "editter" to "editor", as I wasn't sure whether it was the intended name of the project or a spelling mistake

I suggest when merging this PR (if you do) to use the "squash and merge" function; you click the down arrow beside the <kbd>Merge pull request</kbd> button. Because this might clutter up the commit history.

### CODE REVIEW

**Review by anshulhub — CHANGES_REQUESTED** [review]
hi!
Can you please contribute adding uppercase and lowercase case functionality in the toolbar like bold,italic functionalities are present before i consider merging it.

**Comment by TheTechRobo** [comment]
Do you mean, a function to convert text to uppercase and lowercase?

**Comment by anshulhub** [comment]
> Do you mean, a function to convert text to uppercase and lowercase?

Yes,i require a button which can convert the text in uppercase and vice-versa like bold button is present in toolbar.

**Comment by TheTechRobo** [comment]
I'll see what I can do. I'm not going to create an icon for it though (I'm not very good at stuff like that).

**Comment by anshulhub** [comment]
> I'll see what I can do. I'm not going to create an icon for it though (I'm not very good at stuff like that).

Let me know if you successfully create function.

**Review by anshulhub — APPROVED** [review]

**Comment by TheTechRobo** [comment]
If you still want the function, I'll write it in a separate PR.

**Pull request merged**
